apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::169451752343:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-ygHK4rDXRkvW
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::169451752343:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2025-03-23T21:45:52Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1430"
  uid: 257ad6df-0137-40f9-ace9-04fc7e278778
